### ISSUE TITLE
Binary to Octal

### ISSUE THREAD

**Issue by anitha0203** [anitha0203/Binary#1]
I wasn't able to find this question after searching on google. I'm having trouble understanding the reason for converting binary to decimal while converting binary to octal. If anybody know that Can you please tell me the reason.

**Comment by suryasyam61** [comment]
Octal encoding is divided by 8 into each digit, the use of the same formula in the binary value is incorrect, why is it wrong, since the binary digits are equal to one decimal number the octal formula does not apply to the binary to octal conversion

**Comment by anitha0203** [comment]
Thank you suryasyam
